name: fast_path_workspace
publish_to: none

environment:
  sdk: ^3.5.0

workspace:
  - packages/fast_path
  - packages/fast_path_conformance
  - packages/fast_path_flutter
  - packages/fast_path_bench
  - packages/fast_path_bench_flutter
